### ISSUE TITLE
[Android Bootcamp] Projeect 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by iconcells** [iconcells/todoandroid#1]
My app is complete, please review. /cc @codepathreview @codepath

Also, I have a question to implement additional optional functions.  Can I work on SQLite implementation and I can still have time for submission for review ?

**Comment by nidhi1608** [comment]
Kenneth,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

> Can I work on SQLite implementation and I can still have time for submission for review ?

You should continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo). Once you have that, the next step is to <b>schedule a short 5-10 minute phone conversation</b> [here](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to include best number to reach you at to the invite? Look forward to chatting soon!

**Comment by iconcells** [comment]
My app is complete with implementation of SQLite, please review. /cc @codepathreview @codepath

This version has been implemented SQLite as database.  The design of this implementation is not the best design since that is a quick implementation to implement SQLite with some hard-coded SQL statement.  With this design, it removes all the records from the table and re-insert the records into the table from the to do items (array list).   This implementation is designed to experience the usage of SQLite without much changes with the existing design.  The ideal way of this implementation will be using ORM such as ActiveAndroid.  I will revisit this design in future version.

I experienced some issues during the debugging for SQLite.  How can I look at the SQLite data from Android studio?  I was able to find example using Eclipse to debug and review the data from SQLite, but not for Android studio.  Therefore I use Log.d to output values during my debugging but that is not effective.
